### ISSUE TITLE
  mqtt-node:msgHdlr:warn TypeError: qn._target is not a function

### ISSUE THREAD

**Issue by tosscaster** [lwmqn/mqtt-node#23]
mqtt-node:msgHdlr:warn TypeError: qn._target is not a function
  mqtt-node:msgHdlr:warn     at Object._reqHdlr (\lwm2m\lwmqn-client\node_modules\mqtt-node\lib\msg_handlers.js:131:18)
  mqtt-node:msgHdlr:warn     at \lwm2m\lwmqn-client\node_modules\mqtt-node\lib\init.js:161:19
  mqtt-node:msgHdlr:warn     at processTicksAndRejections (internal/process/task_queues.js:82:9)
  mqtt-node:msgHdlr:warn     at runNextTicks (internal/process/task_queues.js:59:3)
  mqtt-node:msgHdlr:warn     at processImmediate (internal/timers.js:412:9) +7ms

**Comment by amer8** [comment]
Thanks for the error report. Fixed in mqtt-node@0.9.0.
